# Generated by Django 4.1.7 on 2023-03-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='описание товара'),
        ),
    ]
