# Generated by Django 4.1.7 on 2023-03-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
