# Generated by Django 4.1.7 on 2023-03-20 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0004_alter_product_limited_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited_offer_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
