# Generated by Django 4.1.7 on 2023-03-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0005_product_limited_offer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='limited_offer_date',
            field=models.DateTimeField(),
        ),
    ]
