# Generated by Django 4.1.7 on 2023-03-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0006_alter_product_limited_offer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='username',
            field=models.TextField(default='не указан', max_length=100, verbose_name='токен пользователя '),
        ),
    ]
