# Generated by Django 4.1.7 on 2023-03-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0007_alter_comparison_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_free_delivery', models.IntegerField(default=0, verbose_name='минимальня цена покупки')),
                ('delivery_price', models.IntegerField(default=0, verbose_name='цена обычной доставки')),
                ('express_delivery_price', models.IntegerField(default=0, verbose_name='цена экспресс доставки доставки')),
            ],
        ),
    ]
