# Generated by Django 4.1.7 on 2023-03-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0008_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
    ]
