# Generated by Django 4.1.7 on 2023-03-22 21:12

from django.db import migrations, models
import my_store_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store_app', '0009_alter_delivery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставка'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/non.png', null=True, upload_to='static/', validators=[my_store_app.models.Profile.validate_image]),
        ),
    ]
